version: 1.4.10
root_dir: /home/dan/go/src/ip/ipgrid/resources/qs_python/samp_metadata/product/mystic/memtest
manifest:
    product_id: a363ca5c-9867-45f5-a074-a08d4966b07f
    release_id: ed7b9898-18f5-4ac0-905a-4b57970278e5
    company: mystic
    name: memtest
    release: 2.1.2
    uri: mystic/memtest/2-1-2
    product_type: soft_ip
    product_category: ""
    use_semver: false
    package_sources: true
    fp_extensions: .v
    product_index: ipindex
    last_update: 2025-08-07T22:25:27.54181-04:00
    description: '"Memory Test Block for Milkymist SoC v1.0"'
